"""Added columns to game model

Revision ID: 71c9888d2024
Revises: 9e6ea47c4c25
Create Date: 2024-12-02 18:05:12.188558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71c9888d2024'
down_revision = '9e6ea47c4c25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('favourites_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('favourites_count')
        batch_op.drop_column('cover_image')

    # ### end Alembic commands ###
